name: ng
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- traits
- pyface
- traitsui
- imageio
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.24
- pyvistaqt>=0.2.0
- mayavi
- PySurfer
- dipy
- nibabel
- nilearn
- python-picard
- pyqt
- mne
- mffpy>=0.5.7
- tensorflow
- pyedflib
- flask
- dill

- pip:
  - flask_cors
  - flask_socketio
  - Flask-Caching
  - eventlet

# for mne development version (fixes Annotations.to_data_frame() problem) run: $ pip install --upgrade --no-deps https://github.com/mne-tools/mne-python/archive/main.zip
